project:
  type: website

website:
  title: "Steven M. Padin"
  navbar:
    background: "maroon"
    left:
      - "email: smpadin1@gmail.com"
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/smp100
      - icon: instagram
        href: https://instagram.com/padinhundreds
      - icon: youtube
        href: https://youtube.com/padinhundreds
format:
  html:
    theme: 
      light: darkly

editor: visual

