project:
  type: website

website:
  title: "Steven M. Padin"
  navbar:
    background: "maroon"
    left:
      - about.qmd
      
    right:
      - icon: linkedin
        href: https://linkedin.com/in/smp100
      - icon: instagram
        href: https://instagram.com/padinhundreds
      - icon: youtube
        href: https://www.youtube.com/@padinhundreds/videos
      - "smpadin1@gmail.com"
format:
  html:
    theme: 
      light: darkly

editor: visual

