project:
  type: website

website:
  title: "Steven M. Padin"
  navbar:
    background: "maroon"
    right:
      - "email: smpadin1@gmail.com"
    left:
      - about.qmd
      - icon: Linkedin
        href: https://linkedin.com/in/smp100
      - icon: instagram
        href: https://instagram.com/padinhundreds
format:
  html:
    theme: 
      light: darkly

editor: visual

